on:
    push:
        # branches: [ main ] # Uncomment to limit to specific branches
    pull_request:
    workflow_dispatch:

jobs:
    pdf:
        uses: andrerocco/markdown-to-pdf-action/.github/workflows/workflow.yml@main
        with:
            files: |
                **/*.md
            global_css: |
                **/theme.css
            exclude: |
                **/README.md
                **/node_modules/**
                **/.git/**
                **/.github/**
            artifact_name: Resume
